// web/src/features/chat/components/sidebar.tsx
'use client'

import { Plus } from 'lucide-react'
import { useState } from 'react'

import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { WorkspaceSelector } from '@/features/chat/components/workspace-selector'
import type { CreateWorkspaceOptions } from '@/lib/api'
import type { Agent, SessionMeta, Workspace } from '@/lib/types'
import { useI18n } from '@/features/i18n/i18n-provider'
import { formatTime } from '@/utils/format'

export function Sidebar({
  agents,
  currentSessionId,
  currentWorkspaceId,
  onAddWorkspace,
  onCollapse,
  onCreateSession,
  onRemoveSession,
  onSetWorkspace,
  onSelectSession,
  sessions,
  workspaces,
}: {
  agents: Agent[]
  currentSessionId: string | null
  currentWorkspaceId: string
  onAddWorkspace: (
    name: string,
    path: string,
    options?: CreateWorkspaceOptions,
  ) => Promise<string | null>
  onCollapse: () => void
  onCreateSession: () => Promise<void>
  onRemoveSession: (sessionId: string) => Promise<void>
  onSetWorkspace: (workspaceId: string) => void
  onSelectSession: (sessionId: string) => Promise<void>
  sessions: SessionMeta[]
  workspaces: Workspace[]
}) {
  const { t } = useI18n()
  const [deleteTarget, setDeleteTarget] = useState<SessionMeta | null>(null)

  return (
    <aside className="flex h-full w-[260px] flex-shrink-0 flex-col border-r border-border bg-card">
      <WorkspaceSelector
        agents={agents}
        currentWorkspaceId={currentWorkspaceId}
        onAddWorkspace={onAddWorkspace}
        onCollapse={onCollapse}
        onSelectWorkspace={onSetWorkspace}
        workspaces={workspaces}
      />
      <div className="flex items-center justify-between px-4 pb-3 pt-5">
        <h2 className="text-[11px] font-bold uppercase tracking-[0.1em] text-muted-foreground">Chats</h2>
        <button
          className="flex h-6 w-6 items-center justify-center rounded-sm border border-border bg-transparent text-[rgb(var(--color-text-secondary))] transition hover:bg-accent hover:text-foreground"
          onClick={() => void onCreateSession()}
          title={t('sidebar.new_chat')}
          type="button"
        >
          <Plus className="h-3.5 w-3.5" />
        </button>
      </div>
      <div className="legacy-hidden-scrollbar flex-1 overflow-y-auto px-2 pb-2">
        {sessions.length ? (
          sessions.map((session) => (
            <div
              className={`group relative mb-0.5 rounded-md border border-transparent px-3 py-[10px] transition ${
                session.id === currentSessionId
                  ? 'bg-muted'
                  : 'bg-transparent hover:bg-accent'
              }`}
              key={session.id}
            >
              {session.id === currentSessionId ? (
                <span className="absolute left-0 top-1/2 h-3 w-0.5 -translate-y-1/2 rounded-r-sm bg-primary" />
              ) : null}
              <button
                className="w-full pr-5 text-left"
                onClick={() => void onSelectSession(session.id)}
                type="button"
              >
                <div className="flex items-center gap-2">
                  <span
                    className={`min-w-0 flex-1 truncate text-[13px] font-medium transition-colors ${
                      session.id === currentSessionId
                        ? 'text-foreground'
                        : 'text-[rgb(var(--color-text-secondary))] group-hover:text-foreground'
                    }`}
                  >
                    {session.title}
                  </span>
                  <span className="flex-shrink-0 text-[10px] text-muted-foreground">
                    {formatTime(session.updatedAt)}
                  </span>
                </div>
              </button>
              <button
                className="absolute right-2 top-1/2 flex h-5 w-5 -translate-y-1/2 items-center justify-center rounded-sm bg-background text-[rgb(var(--color-text-tertiary))] opacity-0 transition hover:bg-destructive hover:text-destructive-foreground group-hover:opacity-100"
                onClick={() => setDeleteTarget(session)}
                title="Delete"
                type="button"
              >
                &times;
              </button>
            </div>
          ))
        ) : (
          <div className="px-4 py-10 text-center text-xs text-muted-foreground">
            No chats in this workspace
          </div>
        )}
      </div>

      <Dialog onOpenChange={(open) => !open && setDeleteTarget(null)} open={Boolean(deleteTarget)}>
        <DialogContent className="border-border bg-[rgb(var(--color-bg-muted))] p-6">
          <DialogHeader className="space-y-2">
            <DialogTitle>Delete Chat</DialogTitle>
            <DialogDescription>Are you sure you want to delete this chat?</DialogDescription>
          </DialogHeader>
          <div className="mt-5 flex justify-end gap-3">
            <Button className="rounded-md" onClick={() => setDeleteTarget(null)} type="button" variant="outline">
              Cancel
            </Button>
            <Button
              className="rounded-md"
              onClick={async () => {
                if (deleteTarget) {
                  await onRemoveSession(deleteTarget.id)
                }
                setDeleteTarget(null)
              }}
              type="button"
              variant="destructive"
            >
              Delete
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </aside>
  )
}

// web/src/components/Sidebar.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useSessionStore } from '../stores/session'
import { formatTime } from '../utils/format'
import WorkspaceSelector from './WorkspaceSelector.vue'
import { useI18n } from '../composables/useI18n'

const emit = defineEmits<{ collapse: [] }>()

const store = useSessionStore()
const { filteredSessions, currentSessionId } = store
const { t } = useI18n()

const deleteModalOpen = ref(false)
const deleteTargetId = ref<string | null>(null)

function handleDelete(e: Event, id: string) {
  e.stopPropagation()
  deleteTargetId.value = id
  deleteModalOpen.value = true
}

function confirmDelete() {
  if (deleteTargetId.value) {
    store.removeSession(deleteTargetId.value)
  }
  closeModal()
}

function closeModal() {
  deleteModalOpen.value = false
  deleteTargetId.value = null
}
</script>

<template>
  <aside class="sidebar">
    <WorkspaceSelector @collapse="emit('collapse')" />
    <div class="sidebar-header">
      <h2>Chats</h2>
      <button class="new-btn" :title="t('sidebar.new_chat')" @click="store.createNewSession">
        +
      </button>
    </div>
    <div class="session-list">
      <div
        v-for="session in filteredSessions"
        :key="session.id"
        class="session-item"
        :class="{ active: session.id === currentSessionId }"
        @click="store.selectSession(session.id)"
      >
        <div class="session-row">
          <span class="session-title">{{ session.title }}</span>
          <span class="session-time">{{ formatTime(session.updatedAt) }}</span>
        </div>
        <button
          class="session-delete"
          title="Delete"
          @click="(e) => handleDelete(e, session.id)"
        >
          &times;
        </button>
      </div>
      <div v-if="filteredSessions.length === 0" class="no-sessions">
        No chats in this workspace
      </div>
    </div>

    <!-- Delete Confirm Modal -->
    <Teleport to="body">
      <div v-if="deleteModalOpen" class="modal-overlay" @click="closeModal">
        <div class="modal-content" @click.stop>
          <div class="modal-title">Delete Chat</div>
          <div class="modal-body">Are you sure you want to delete this chat?</div>
          <div class="modal-actions">
            <button class="btn-cancel" @click="closeModal">Cancel</button>
            <button class="btn-delete" @click="confirmDelete">Delete</button>
          </div>
        </div>
      </div>
    </Teleport>
  </aside>
</template>

<style scoped>
.sidebar {
  width: 260px;
  background: var(--bg-surface);
  border-right: 1px solid var(--bg-element);
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  transition: width var(--duration-normal) var(--ease-snappy);
}

.sidebar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px 16px 12px;
}

.sidebar-header h2 {
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color: var(--text-tertiary);
  margin: 0;
}

.new-btn {
  width: 24px;
  height: 24px;
  border: 1px solid var(--bg-element);
  background: transparent;
  color: var(--text-secondary);
  border-radius: var(--radius-sm);
  font-size: 14px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all var(--duration-fast);
}

.new-btn:hover {
  background: var(--bg-surface-hover);
  color: var(--text-primary);
  border-color: var(--text-tertiary);
}

.session-list {
  flex: 1;
  overflow-y: auto;
  padding: 8px;
  /* Visual scrollbar hiding but functional */
  scrollbar-width: none;
}

.session-list::-webkit-scrollbar {
  display: none;
}

.session-item {
  padding: 10px 12px;
  border-radius: var(--radius-md);
  cursor: pointer;
  margin-bottom: 2px;
  position: relative;
  transition: background var(--duration-fast), transform var(--duration-fast);
  border: 1px solid transparent;
}

.session-item:hover {
  background: var(--bg-surface-hover);
}

.session-item.active {
  background: var(--bg-element);
}

.session-item.active::before {
  content: '';
  position: absolute;
  left: 0;
  top: 50%;
  transform: translateY(-50%);
  height: 12px;
  width: 2px;
  background-color: var(--accent-primary);
  border-radius: 0 2px 2px 0;
}

.session-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.session-title {
  flex: 1;
  font-size: 13px;
  font-weight: 500;
  color: var(--text-secondary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  transition: color var(--duration-fast);
}

.session-item.active .session-title,
.session-item:hover .session-title {
  color: var(--text-primary);
}

.session-time {
  font-size: 10px;
  color: var(--text-tertiary);
  flex-shrink: 0;
}

.session-delete {
  position: absolute;
  right: 8px;
  top: 50%;
  transform: translateY(-50%);
  width: 20px;
  height: 20px;
  border: none;
  background: var(--bg-root);
  color: var(--text-tertiary);
  font-size: 14px;
  cursor: pointer;
  border-radius: var(--radius-sm);
  opacity: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all var(--duration-fast);
}

.session-item:hover .session-delete {
  opacity: 1;
}

.session-delete:hover {
  background: var(--accent-error);
  color: #fff;
}

.no-sessions {
  text-align: center;
  color: var(--text-tertiary);
  padding: 40px 20px;
  font-size: 12px;
}
</style>

<style>
/* Modal styles (global for Teleport) */
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.8);
  backdrop-filter: blur(2px);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 2000;
}

.modal-content {
  background: var(--bg-element);
  border: 1px solid var(--accent-subtle);
  border-radius: var(--radius-lg);
  padding: 24px;
  min-width: 320px;
  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.6);
}

.modal-title {
  font-size: 16px;
  font-weight: 600;
  color: var(--text-primary);
  margin-bottom: 8px;
}

.modal-body {
  font-size: 13px;
  color: var(--text-secondary);
  margin-bottom: 24px;
}

.modal-actions {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}

.modal-actions button {
  padding: 8px 16px;
  border-radius: var(--radius-md);
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  transition: all var(--duration-fast);
}

.btn-cancel {
  background: transparent;
  border: 1px solid var(--accent-subtle);
  color: var(--text-secondary);
}

.btn-cancel:hover {
  border-color: var(--text-primary);
  color: var(--text-primary);
}

.btn-delete {
  background: var(--accent-error);
  border: 1px solid var(--accent-error);
  color: white;
}

.btn-delete:hover {
  opacity: 0.9;
}
</style>
